[project]
name = "Titular"
authors = [{ name = "Pedro Sousa Lacerda", email = "pslacerda@gmail.com" }]
version = "0.1.0"
requires-python = ">3.14, <3.15"
description = "A química do pH e pKa explicada e ilustrada."
dependencies = [
    "dimorphite-dl",
    "rdkit",
    "streamlit",
    "plotly-express",
    "polars",
    "numpy",
    "ordered-set",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["titular"]
