services:
  - type: web
    name: Titular
    env: python
    region: ohio  # melhor latência pra BR
    plan: free
    buildCommand: |
      apt-get update
      apt-get install libxrender1 libgl1-mesa-glx
      npm install
      npm run build
      uv cache prune
      uv sync --frozen
    startCommand: |
      streamlit run titular/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
    - key: PYTHON_VERSION
      value: 3.14.x
    - key: NODE_VERSION
      value: 26.x